// Generated from the permission catalogue (python -m assistant.iam catalogue --typescript). Do not edit.
export const CATALOGUE_VERSION = 3;

export const PERMISSION_KEYS = [
  "account.read_self",
  "account.update_self",
  "account.password.change",
  "account.sessions.read_self",
  "account.sessions.revoke_self",
  "iam.users.read",
  "iam.users.invite",
  "iam.users.update",
  "iam.users.suspend",
  "iam.users.reactivate",
  "iam.users.recovery.initiate",
  "iam.users.deactivate",
  "iam.sessions.read",
  "iam.sessions.revoke",
  "iam.roles.read",
  "iam.roles.create",
  "iam.roles.update",
  "iam.roles.delete",
  "iam.roles.assign",
  "iam.groups.read",
  "iam.groups.create",
  "iam.groups.update",
  "iam.groups.delete",
  "iam.groups.members.manage",
  "iam.access.explain",
  "iam.access.review",
  "iam.access.requests.create",
  "iam.access.requests.read_own",
  "iam.access.requests.cancel_own",
  "iam.access.requests.decide",
  "iam.access.deny.manage",
  "iam.services.read",
  "iam.services.create",
  "iam.services.update",
  "iam.services.credentials.rotate",
  "iam.services.revoke",
  "platform.settings.read",
  "platform.settings.manage",
  "platform.services.read",
  "platform.services.restart",
  "platform.models.manage",
  "platform.integrations.manage",
  "platform.secrets.rotate",
  "platform.backup.manage",
  "platform.restore.execute",
  "platform.cross_space.read",
  "platform.emergency.recover",
  "spaces.create",
  "spaces.read",
  "spaces.update",
  "spaces.archive",
  "spaces.restore",
  "spaces.delete",
  "spaces.export",
  "spaces.members.read",
  "spaces.members.invite",
  "spaces.members.manage",
  "spaces.policy.manage",
  "resources.permissions.read",
  "resources.permissions.manage",
  "resources.classification.manage",
  "resources.ownership.transfer",
  "collections.read",
  "collections.create",
  "collections.update",
  "collections.move",
  "collections.delete",
  "sources.register",
  "sources.upload",
  "sources.metadata.update",
  "sources.ingest",
  "sources.reindex",
  "sources.archive",
  "sources.restore",
  "sources.delete",
  "documents.read",
  "documents.draft.read",
  "documents.create",
  "documents.edit",
  "documents.submit",
  "documents.withdraw",
  "documents.approve",
  "documents.reject",
  "documents.publish",
  "documents.versions.read",
  "documents.versions.restore",
  "documents.download",
  "documents.transfer",
  "comments.read",
  "comments.create",
  "comments.update_own",
  "comments.delete_own",
  "comments.moderate",
  "assets.upload",
  "assets.read",
  "assets.delete",
  "knowledge.search",
  "knowledge.ask",
  "knowledge.citations.read",
  "knowledge.retrieval_trace.read",
  "governance.read",
  "governance.scan.run",
  "governance.reviews.run",
  "governance.findings.resolve",
  "governance.exceptions.accept",
  "governance.self_approve",
  "external_sources.read",
  "external_sources.register",
  "external_sources.refresh",
  "external_sources.delete",
  "regulatory.read",
  "regulatory.reviews.run",
  "regulatory.decisions.approve",
  "processes.read",
  "processes.diagrams.generate",
  "processes.capture.create",
  "processes.edit",
  "processes.export",
  "eam.read",
  "eam.export",
  "ontology.read",
  "ontology.query",
  "ontology.edit",
  "ontology.rebuild",
  "ontology.export",
  "agent.run",
  "agent.proposals.read",
  "agent.proposals.approve",
  "agent.proposals.reject",
  "agent.actions.execute",
  "analytics.read",
  "analytics.raw.read",
  "analytics.export",
  "analytics.improvements.create",
  "analytics.improvements.manage",
  "tibi.use",
  "tibi.voice.use",
  "tibi.rehearsal.use",
  "tibi.knowledge.read",
  "tibi.knowledge.edit",
  "tibi.knowledge.approve",
  "tibi.spoken.edit",
  "tibi.spoken.approve",
  "tibi.persona.manage",
  "avatar.use",
  "avatar.session.create",
  "conversations.read_own",
  "conversations.delete_own",
  "conversations.read_all",
  "conversations.review",
  "conversations.export",
  "conversations.delete_all",
  "jobs.read_own",
  "jobs.cancel_own",
  "jobs.read_all",
  "jobs.cancel_all",
  "exports.create",
  "exports.download",
  "exports.revoke",
  "audit.read",
  "audit.export",
  "diagnostics.read",
  "diagnostics.traces.read",
] as const;

export type Permission = (typeof PERMISSION_KEYS)[number];

export interface PermissionInfo {
  namespace: string;
  description: string;
  scopes: string[];
  risky: boolean;
  /** Why it guards nothing yet; a custom role cannot be given it (REF S5). */
  reserved: string;
}

export const PERMISSIONS: Record<Permission, PermissionInfo> = {
  "account.read_self": { namespace: "account", description: "See my own account", scopes: ["own"], risky: false, reserved: "implied: every signed-in person reads their own account (the signed-in marker)" },
  "account.update_self": { namespace: "account", description: "Change my own name and profile", scopes: ["own"], risky: false, reserved: "" },
  "account.password.change": { namespace: "account", description: "Change my own password", scopes: ["own"], risky: false, reserved: "" },
  "account.sessions.read_self": { namespace: "account", description: "See where I am signed in", scopes: ["own"], risky: false, reserved: "" },
  "account.sessions.revoke_self": { namespace: "account", description: "Sign out my other sessions", scopes: ["own"], risky: false, reserved: "" },
  "iam.users.read": { namespace: "iam.users", description: "See the people on this installation", scopes: ["platform"], risky: false, reserved: "" },
  "iam.users.invite": { namespace: "iam.users", description: "Invite a person", scopes: ["platform"], risky: false, reserved: "" },
  "iam.users.update": { namespace: "iam.users", description: "Change a person's account details", scopes: ["platform"], risky: false, reserved: "" },
  "iam.users.suspend": { namespace: "iam.users", description: "Suspend a person's account", scopes: ["platform"], risky: false, reserved: "" },
  "iam.users.reactivate": { namespace: "iam.users", description: "Reactivate a suspended account", scopes: ["platform"], risky: false, reserved: "" },
  "iam.users.recovery.initiate": { namespace: "iam.users", description: "Start password recovery for a person", scopes: ["platform"], risky: true, reserved: "" },
  "iam.users.deactivate": { namespace: "iam.users", description: "Deactivate (offboard) a person", scopes: ["platform"], risky: true, reserved: "" },
  "iam.sessions.read": { namespace: "iam.sessions", description: "See everyone's sessions", scopes: ["platform"], risky: false, reserved: "" },
  "iam.sessions.revoke": { namespace: "iam.sessions", description: "Sign someone out", scopes: ["platform"], risky: false, reserved: "" },
  "iam.roles.read": { namespace: "iam.roles", description: "See roles and what they allow", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.roles.create": { namespace: "iam.roles", description: "Create a custom role", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.roles.update": { namespace: "iam.roles", description: "Change a custom role", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.roles.delete": { namespace: "iam.roles", description: "Delete a custom role", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.roles.assign": { namespace: "iam.roles", description: "Give or take a role", scopes: ["platform", "space"], risky: true, reserved: "" },
  "iam.groups.read": { namespace: "iam.groups", description: "See groups", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.groups.create": { namespace: "iam.groups", description: "Create a group", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.groups.update": { namespace: "iam.groups", description: "Change a group", scopes: ["platform", "space"], risky: false, reserved: "groups are not built" },
  "iam.groups.delete": { namespace: "iam.groups", description: "Delete a group", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.groups.members.manage": { namespace: "iam.groups", description: "Add and remove group members", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.access.explain": { namespace: "iam.access", description: "Explain why someone can or cannot do something", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.access.review": { namespace: "iam.access", description: "Run an access review", scopes: ["platform", "space"], risky: false, reserved: "access reviews are deferred (IAM guide, section 5)" },
  "iam.access.requests.create": { namespace: "iam.access", description: "Ask for access", scopes: ["own"], risky: false, reserved: "" },
  "iam.access.requests.read_own": { namespace: "iam.access", description: "See my own access requests", scopes: ["own"], risky: false, reserved: "access requests are deferred (IAM guide, section 5)" },
  "iam.access.requests.cancel_own": { namespace: "iam.access", description: "Cancel my own access request", scopes: ["own"], risky: false, reserved: "" },
  "iam.access.requests.decide": { namespace: "iam.access", description: "Approve or reject access requests", scopes: ["platform", "space"], risky: false, reserved: "" },
  "iam.access.deny.manage": { namespace: "iam.access", description: "Add or lift an explicit deny", scopes: ["platform", "space"], risky: true, reserved: "" },
  "iam.services.read": { namespace: "iam.services", description: "See service accounts", scopes: ["platform", "space"], risky: false, reserved: "service principals: REF S12" },
  "iam.services.create": { namespace: "iam.services", description: "Create a service account", scopes: ["platform", "space"], risky: false, reserved: "service principals: REF S12" },
  "iam.services.update": { namespace: "iam.services", description: "Change a service account", scopes: ["platform", "space"], risky: false, reserved: "service principals: REF S12" },
  "iam.services.credentials.rotate": { namespace: "iam.services", description: "Issue or rotate a service credential", scopes: ["platform", "space"], risky: true, reserved: "service principals: REF S12" },
  "iam.services.revoke": { namespace: "iam.services", description: "Revoke a service account", scopes: ["platform", "space"], risky: false, reserved: "service principals: REF S12" },
  "platform.settings.read": { namespace: "platform", description: "See platform settings", scopes: ["platform"], risky: false, reserved: "" },
  "platform.settings.manage": { namespace: "platform", description: "Change platform and security settings", scopes: ["platform"], risky: true, reserved: "" },
  "platform.services.read": { namespace: "platform", description: "See the services and their state", scopes: ["platform"], risky: false, reserved: "no route yet; the Settings page reads service health without it" },
  "platform.services.restart": { namespace: "platform", description: "Start or restart a service", scopes: ["platform"], risky: true, reserved: "" },
  "platform.models.manage": { namespace: "platform", description: "Change the models in use", scopes: ["platform"], risky: true, reserved: "model changes as controlled product changes: REF S41" },
  "platform.integrations.manage": { namespace: "platform", description: "Change integrations", scopes: ["platform"], risky: true, reserved: "no integrations are built" },
  "platform.secrets.rotate": { namespace: "platform", description: "Replace a secret", scopes: ["platform"], risky: true, reserved: "managed secrets come with the network profile: REF S47" },
  "platform.backup.manage": { namespace: "platform", description: "Make and manage backups", scopes: ["platform"], risky: true, reserved: "backup and tested restore: REF S30" },
  "platform.restore.execute": { namespace: "platform", description: "Restore from a backup", scopes: ["platform"], risky: true, reserved: "backup and tested restore: REF S30" },
  "platform.cross_space.read": { namespace: "platform", description: "Read across all organisations", scopes: ["platform"], risky: true, reserved: "the All organisations mode is deferred (IAM guide, section 5)" },
  "platform.emergency.recover": { namespace: "platform", description: "Emergency recovery (local procedure only)", scopes: ["platform"], risky: true, reserved: "a host procedure only (python -m assistant.iam recover), never an API" },
  "spaces.create": { namespace: "spaces", description: "Create a space", scopes: ["platform"], risky: false, reserved: "" },
  "spaces.read": { namespace: "spaces", description: "See the space and its name", scopes: ["space"], risky: false, reserved: "" },
  "spaces.update": { namespace: "spaces", description: "Rename or describe the space", scopes: ["space"], risky: false, reserved: "" },
  "spaces.archive": { namespace: "spaces", description: "Archive the space", scopes: ["space"], risky: false, reserved: "" },
  "spaces.restore": { namespace: "spaces", description: "Restore an archived space", scopes: ["space"], risky: false, reserved: "" },
  "spaces.delete": { namespace: "spaces", description: "Delete the space", scopes: ["space"], risky: true, reserved: "deletion of an organisation, proven complete: REF S31" },
  "spaces.export": { namespace: "spaces", description: "Export the whole space", scopes: ["space"], risky: true, reserved: "export of an organisation: REF S31" },
  "spaces.members.read": { namespace: "spaces", description: "See the space's members", scopes: ["space"], risky: false, reserved: "" },
  "spaces.members.invite": { namespace: "spaces", description: "Invite people to the space", scopes: ["space"], risky: false, reserved: "" },
  "spaces.members.manage": { namespace: "spaces", description: "Change or remove the space's members", scopes: ["space"], risky: false, reserved: "" },
  "spaces.policy.manage": { namespace: "spaces", description: "Change the space's access policies", scopes: ["space"], risky: true, reserved: "no per-space policy route; solo-operator mode is set with platform.settings.manage" },
  "resources.permissions.read": { namespace: "resources", description: "See who can reach a resource", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "resources.permissions.manage": { namespace: "resources", description: "Change who can reach a resource", scopes: ["space", "collection", "resource"], risky: true, reserved: "" },
  "resources.classification.manage": { namespace: "resources", description: "Classify a resource", scopes: ["space", "collection", "resource"], risky: false, reserved: "enforced classification: REF S13, REF S23" },
  "resources.ownership.transfer": { namespace: "resources", description: "Transfer ownership of a resource", scopes: ["space", "collection", "resource"], risky: false, reserved: "an owner on every source: REF S23" },
  "collections.read": { namespace: "collections", description: "See folders", scopes: ["space", "collection"], risky: false, reserved: "" },
  "collections.create": { namespace: "collections", description: "Create a folder", scopes: ["space", "collection"], risky: false, reserved: "" },
  "collections.update": { namespace: "collections", description: "Rename a folder", scopes: ["space", "collection"], risky: false, reserved: "" },
  "collections.move": { namespace: "collections", description: "Move a folder or document", scopes: ["space", "collection"], risky: false, reserved: "" },
  "collections.delete": { namespace: "collections", description: "Delete a folder", scopes: ["space", "collection"], risky: false, reserved: "" },
  "sources.register": { namespace: "sources", description: "Register a source", scopes: ["space", "collection", "resource"], risky: false, reserved: "registering a source is an upload (sources.upload)" },
  "sources.upload": { namespace: "sources", description: "Upload a source", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "sources.metadata.update": { namespace: "sources", description: "Change a source's details", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "sources.ingest": { namespace: "sources", description: "Ingest a source", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "sources.reindex": { namespace: "sources", description: "Reindex a source", scopes: ["space", "collection", "resource"], risky: false, reserved: "no reindex route; publishing re-ingests" },
  "sources.archive": { namespace: "sources", description: "Archive a source", scopes: ["space", "collection", "resource"], risky: false, reserved: "archive and restore: REF S24" },
  "sources.restore": { namespace: "sources", description: "Restore an archived source", scopes: ["space", "collection", "resource"], risky: false, reserved: "archive and restore: REF S24" },
  "sources.delete": { namespace: "sources", description: "Delete a source", scopes: ["space", "collection", "resource"], risky: true, reserved: "" },
  "documents.read": { namespace: "documents", description: "Read approved documents", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.draft.read": { namespace: "documents", description: "Read drafts and review material", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.create": { namespace: "documents", description: "Create a document", scopes: ["space", "collection", "resource"], risky: false, reserved: "documents are created by upload (sources.upload)" },
  "documents.edit": { namespace: "documents", description: "Edit a document", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.submit": { namespace: "documents", description: "Submit a draft for review", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.withdraw": { namespace: "documents", description: "Withdraw a submission", scopes: ["space", "collection", "resource"], risky: false, reserved: "withdrawing one's own submission is not built" },
  "documents.approve": { namespace: "documents", description: "Approve a revision", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.reject": { namespace: "documents", description: "Reject a revision", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.publish": { namespace: "documents", description: "Publish an approved revision", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.versions.read": { namespace: "documents", description: "See a document's history", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.versions.restore": { namespace: "documents", description: "Restore an earlier version as a draft", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "documents.download": { namespace: "documents", description: "Download the original file", scopes: ["space", "collection", "resource"], risky: false, reserved: "no download route" },
  "documents.transfer": { namespace: "documents", description: "Transfer a document to another space", scopes: ["space", "collection", "resource"], risky: true, reserved: "" },
  "comments.read": { namespace: "comments", description: "Read comments", scopes: ["space", "collection", "resource", "own"], risky: false, reserved: "" },
  "comments.create": { namespace: "comments", description: "Comment", scopes: ["space", "collection", "resource", "own"], risky: false, reserved: "" },
  "comments.update_own": { namespace: "comments", description: "Edit my own comments", scopes: ["own"], risky: false, reserved: "editing a comment is not built" },
  "comments.delete_own": { namespace: "comments", description: "Delete my own comments", scopes: ["own"], risky: false, reserved: "deleting a comment needs comments.moderate; deleting one's own is not built" },
  "comments.moderate": { namespace: "comments", description: "Edit or remove anyone's comments", scopes: ["space", "collection", "resource", "own"], risky: false, reserved: "" },
  "assets.upload": { namespace: "assets", description: "Insert an image", scopes: ["resource"], risky: false, reserved: "" },
  "assets.read": { namespace: "assets", description: "See images in documents", scopes: ["resource"], risky: false, reserved: "" },
  "assets.delete": { namespace: "assets", description: "Remove an image", scopes: ["resource"], risky: false, reserved: "images are removed with the documents that use them (REF S4)" },
  "knowledge.search": { namespace: "knowledge", description: "Search", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "knowledge.ask": { namespace: "knowledge", description: "Ask questions", scopes: ["space", "collection", "resource"], risky: false, reserved: "" },
  "knowledge.citations.read": { namespace: "knowledge", description: "Open cited evidence", scopes: ["space", "collection", "resource"], risky: false, reserved: "citations come with the answer; evidence receipts: REF S18" },
  "knowledge.retrieval_trace.read": { namespace: "knowledge", description: "See retrieval traces", scopes: ["space", "collection", "resource"], risky: true, reserved: "traces are part of the answer today; a separate grant: REF S18" },
  "governance.read": { namespace: "governance", description: "See governance findings", scopes: ["space", "resource"], risky: false, reserved: "" },
  "governance.scan.run": { namespace: "governance", description: "Run a quick scan", scopes: ["space", "resource"], risky: false, reserved: "" },
  "governance.reviews.run": { namespace: "governance", description: "Run a review", scopes: ["space", "resource"], risky: false, reserved: "" },
  "governance.findings.resolve": { namespace: "governance", description: "Resolve findings", scopes: ["space", "resource"], risky: false, reserved: "" },
  "governance.exceptions.accept": { namespace: "governance", description: "Accept an exception", scopes: ["space", "resource"], risky: false, reserved: "" },
  "governance.self_approve": { namespace: "governance", description: "Approve my own work (solo-operator mode)", scopes: ["space", "resource"], risky: true, reserved: "" },
  "external_sources.read": { namespace: "external_sources", description: "See external sources", scopes: ["space", "resource"], risky: false, reserved: "" },
  "external_sources.register": { namespace: "external_sources", description: "Register an external source", scopes: ["space", "resource"], risky: false, reserved: "every change to a public source needs external_sources.refresh today; REF S46" },
  "external_sources.refresh": { namespace: "external_sources", description: "Refresh an external source", scopes: ["space", "resource"], risky: false, reserved: "" },
  "external_sources.delete": { namespace: "external_sources", description: "Remove an external source", scopes: ["space", "resource"], risky: false, reserved: "" },
  "regulatory.read": { namespace: "regulatory", description: "See regulatory reviews", scopes: ["space", "resource"], risky: false, reserved: "" },
  "regulatory.reviews.run": { namespace: "regulatory", description: "Run a regulatory review", scopes: ["space", "resource"], risky: false, reserved: "" },
  "regulatory.decisions.approve": { namespace: "regulatory", description: "Approve a regulatory decision", scopes: ["space", "resource"], risky: false, reserved: "" },
  "processes.read": { namespace: "processes", description: "See processes and maps", scopes: ["space", "resource"], risky: false, reserved: "" },
  "processes.diagrams.generate": { namespace: "processes", description: "Generate process maps", scopes: ["space", "resource"], risky: false, reserved: "" },
  "processes.capture.create": { namespace: "processes", description: "Capture a process (interviews)", scopes: ["space", "resource"], risky: false, reserved: "" },
  "processes.edit": { namespace: "processes", description: "Edit a process", scopes: ["space", "resource"], risky: false, reserved: "processes are derived from approved documents; nothing edits them directly" },
  "processes.export": { namespace: "processes", description: "Export processes", scopes: ["space", "resource"], risky: false, reserved: "no process export" },
  "eam.read": { namespace: "eam", description: "See the activity model", scopes: ["space", "resource"], risky: false, reserved: "" },
  "eam.export": { namespace: "eam", description: "Export the activity model", scopes: ["space", "resource"], risky: false, reserved: "no activity-model export" },
  "ontology.read": { namespace: "ontology", description: "See the facts map", scopes: ["space", "resource"], risky: false, reserved: "" },
  "ontology.query": { namespace: "ontology", description: "Query the facts map", scopes: ["space", "resource"], risky: false, reserved: "facts-map queries run inside answering (knowledge.ask) and its views (ontology.read)" },
  "ontology.edit": { namespace: "ontology", description: "Edit the facts map", scopes: ["space", "resource"], risky: false, reserved: "the facts map is derived and rebuilt; nothing edits it directly" },
  "ontology.rebuild": { namespace: "ontology", description: "Rebuild the facts map", scopes: ["space", "resource"], risky: false, reserved: "" },
  "ontology.export": { namespace: "ontology", description: "Export the facts map", scopes: ["space", "resource"], risky: false, reserved: "no facts-map export" },
  "agent.run": { namespace: "agent", description: "Run the agent", scopes: ["space", "resource"], risky: false, reserved: "" },
  "agent.proposals.read": { namespace: "agent", description: "See proposals", scopes: ["space", "resource"], risky: false, reserved: "" },
  "agent.proposals.approve": { namespace: "agent", description: "Approve a proposal", scopes: ["space", "resource"], risky: false, reserved: "" },
  "agent.proposals.reject": { namespace: "agent", description: "Reject a proposal", scopes: ["space", "resource"], risky: false, reserved: "" },
  "agent.actions.execute": { namespace: "agent", description: "Execute an approved action", scopes: ["space", "resource"], risky: true, reserved: "" },
  "analytics.read": { namespace: "analytics", description: "See analytics", scopes: ["space", "resource"], risky: false, reserved: "" },
  "analytics.raw.read": { namespace: "analytics", description: "Read raw questions and prompts", scopes: ["space", "resource"], risky: true, reserved: "" },
  "analytics.export": { namespace: "analytics", description: "Export reports", scopes: ["space", "resource"], risky: false, reserved: "" },
  "analytics.improvements.create": { namespace: "analytics", description: "Propose improvements", scopes: ["space", "resource"], risky: false, reserved: "" },
  "analytics.improvements.manage": { namespace: "analytics", description: "Manage improvement actions", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.use": { namespace: "tibi", description: "Talk with Tibi", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.voice.use": { namespace: "tibi", description: "Use the voice", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.rehearsal.use": { namespace: "tibi", description: "Use rehearsal mode", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.knowledge.read": { namespace: "tibi", description: "See Tibi's knowledge", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.knowledge.edit": { namespace: "tibi", description: "Edit Tibi's knowledge", scopes: ["space", "resource"], risky: false, reserved: "Tibi's knowledge is edited as documents (documents.edit)" },
  "tibi.knowledge.approve": { namespace: "tibi", description: "Approve Tibi's knowledge", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.spoken.edit": { namespace: "tibi", description: "Edit spoken answers", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.spoken.approve": { namespace: "tibi", description: "Approve spoken answers", scopes: ["space", "resource"], risky: false, reserved: "" },
  "tibi.persona.manage": { namespace: "tibi", description: "Change Tibi's persona", scopes: ["platform"], risky: true, reserved: "personas as governed packages: REF S55" },
  "avatar.use": { namespace: "avatar", description: "Use the Digital SME", scopes: ["space"], risky: false, reserved: "" },
  "avatar.session.create": { namespace: "avatar", description: "Start an avatar session", scopes: ["space"], risky: false, reserved: "" },
  "conversations.read_own": { namespace: "conversations", description: "See my own conversations", scopes: ["own"], risky: false, reserved: "conversations belong to a person: REF S14" },
  "conversations.delete_own": { namespace: "conversations", description: "Delete my own conversations", scopes: ["own"], risky: false, reserved: "conversations belong to a person: REF S14" },
  "conversations.read_all": { namespace: "conversations", description: "Read everyone's conversations in the space", scopes: ["space"], risky: true, reserved: "" },
  "conversations.review": { namespace: "conversations", description: "Review conversation turns", scopes: ["space"], risky: false, reserved: "" },
  "conversations.export": { namespace: "conversations", description: "Export conversations", scopes: ["space"], risky: true, reserved: "conversation export: REF S14" },
  "conversations.delete_all": { namespace: "conversations", description: "Delete conversations", scopes: ["space"], risky: true, reserved: "retention and deletion of conversations: REF S32" },
  "jobs.read_own": { namespace: "jobs", description: "See my own jobs", scopes: ["own"], risky: false, reserved: "jobs belong to a person: REF S14, durable jobs: REF S33" },
  "jobs.cancel_own": { namespace: "jobs", description: "Cancel my own jobs", scopes: ["own"], risky: false, reserved: "jobs belong to a person: REF S14, durable jobs: REF S33" },
  "jobs.read_all": { namespace: "jobs", description: "See everyone's jobs in the space", scopes: ["space"], risky: false, reserved: "durable jobs: REF S33" },
  "jobs.cancel_all": { namespace: "jobs", description: "Cancel anyone's jobs in the space", scopes: ["space"], risky: false, reserved: "durable jobs: REF S33" },
  "exports.create": { namespace: "exports", description: "Create an export", scopes: ["space", "resource", "own"], risky: false, reserved: "export of an organisation: REF S31" },
  "exports.download": { namespace: "exports", description: "Download an export", scopes: ["space", "resource", "own"], risky: false, reserved: "export of an organisation: REF S31" },
  "exports.revoke": { namespace: "exports", description: "Revoke an export", scopes: ["space", "resource", "own"], risky: false, reserved: "export of an organisation: REF S31" },
  "audit.read": { namespace: "audit", description: "Read the security audit", scopes: ["platform", "space"], risky: false, reserved: "" },
  "audit.export": { namespace: "audit", description: "Export the security audit", scopes: ["platform", "space"], risky: true, reserved: "" },
  "diagnostics.read": { namespace: "diagnostics", description: "See diagnostics", scopes: ["platform", "space"], risky: false, reserved: "" },
  "diagnostics.traces.read": { namespace: "diagnostics", description: "Read traces", scopes: ["platform", "space"], risky: true, reserved: "" },
};

export const NAMESPACES: { key: string; label: string; note: string }[] = [
  { key: "account", label: "My account", note: "Self-service only: nothing here changes a person's authority." },
  { key: "iam.users", label: "People", note: "Accounts on this installation. Recovery never exposes or sets a password." },
  { key: "iam.sessions", label: "Sessions", note: "Session metadata only; never a session's secret." },
  { key: "iam.roles", label: "Roles", note: "Platform roles at the platform; space roles within a space owner's grant ceiling." },
  { key: "iam.groups", label: "Groups", note: "A group grants nothing until a role is bound to it." },
  { key: "iam.access", label: "Access decisions", note: "Explanations never reveal a resource the asker cannot see." },
  { key: "iam.services", label: "Service accounts", note: "Exact scope, a human owner and an expiry are required." },
  { key: "platform", label: "Platform", note: "Secrets are write-only; restore and recovery have their own procedures." },
  { key: "spaces", label: "Spaces", note: "Creating a space is a platform action; the rest belong to the space." },
  { key: "resources", label: "Resource permissions", note: "Never across a space boundary." },
  { key: "collections", label: "Folders", note: "Moving a folder can change who sees what is in it." },
  { key: "sources", label: "Sources", note: "Derived data shares the source's policy." },
  { key: "documents", label: "Documents", note: "Reading means approved content; drafts, versions and downloads are separate." },
  { key: "comments", label: "Comments", note: "The parent document's permission is always required as well." },
  { key: "assets", label: "Images", note: "An image is only served with readable parent content." },
  { key: "knowledge", label: "Knowledge", note: "Search and answers use approved, permitted evidence only." },
  { key: "governance", label: "Governance", note: "Independent review applies unless a space is in solo-operator mode." },
  { key: "external_sources", label: "External sources", note: "Registration cannot reach arbitrary internal addresses." },
  { key: "regulatory", label: "Regulatory", note: "Approval does not widen source access." },
  { key: "processes", label: "Processes", note: "Outputs inherit the evidence they were made from." },
  { key: "eam", label: "Enterprise Activity Model", note: "Hidden nodes, edges and totals are filtered." },
  { key: "ontology", label: "Facts map", note: "Traversal cannot cross unauthorised evidence." },
  { key: "agent", label: "Ontology agent", note: "Executing an action also needs that action's own permission." },
  { key: "analytics", label: "Analytics", note: "Aggregates and raw question text are controlled separately." },
  { key: "tibi", label: "Tibi", note: "No implicit family-wide evidence; the persona is a platform setting." },
  { key: "avatar", label: "Digital SME", note: "Rendered by a managed service: the reply text leaves the machine. It answers from the OpsAtlas family only; no organisation's content reaches it." },
  { key: "conversations", label: "Conversations", note: "read_all means the space, never the installation." },
  { key: "jobs", label: "Jobs", note: "The underlying operation's permission is still required." },
  { key: "exports", label: "Exports", note: "Also require the domain's export permission and current read access." },
  { key: "audit", label: "Audit", note: "IAM metadata; never document content or conversation text." },
  { key: "diagnostics", label: "Diagnostics", note: "Secrets are redacted and data scope holds even for debug tools." },
];
