#!/usr/bin/env python3
"""The release facts in ARCHITECTURE_STATUS.md, generated from what the code and its registries say (REF S7).

The status page drifted from the code more than once: it named an older Tibi engine, and listed query rewriting and
reranking without saying the Sales profile turns them off. The facts that drift are now generated between two markers
in the page, and a test fails when the committed block differs from what this script produces.

    python scripts/release_facts.py            # print the block
    python scripts/release_facts.py --write    # replace the block in ARCHITECTURE_STATUS.md
    python scripts/release_facts.py --check    # exit 1 when the page is stale (the test does the same)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "ARCHITECTURE_STATUS.md"
START, END = "<!-- release facts: generated by scripts/release_facts.py; do not edit by hand -->", "<!-- /release facts -->"


def _engine() -> list[str]:
    registry = json.loads((ROOT / "config/tibi/engine-versions.json").read_text())
    current = next(v for v in registry["versions"] if v["version"] == registry["current"])
    budget = json.loads((ROOT / "config/tibi/latency-budget.json").read_text())
    replays = sorted((ROOT / "evaluation/results/tibi").glob(f"*latency-replay-engine-{current['version']}.json"))
    models = ", ".join(f"{k} `{v}`" for k, v in sorted(current.get("models", {}).items()))
    lines = [f"| Tibi engine | {current['version']} ({current['date']}), fingerprint `{current['fingerprint']}`; models: {models} |"]
    if replays:
        first = json.loads(replays[-1].read_text())["summary"]["first_audio"]
        limit = budget["replay"]["budget"]
        lines.append(f"| Its latency replay | {first['n']} turns: p50 {first['p50']:,.0f} ms, p95 {first['p95']:,.0f} ms "
                     f"(budget p50 {limit['p50']:,} ms, p95 {limit['p95']:,} ms); `{replays[-1].relative_to(ROOT)}` |")
    else:
        lines.append("| Its latency replay | none recorded for this version |")
    return lines


def _profile() -> list[str]:
    sys.path[:0] = [str(ROOT / "src"), str(ROOT)]
    from assistant import settings
    profile = json.loads((ROOT / "services/opsatlas_sales/profile.json").read_text())
    chosen = {**{name: s.default for name, s in settings.SETTINGS.items()}, **profile.get("set", {})}
    on = lambda name: "on" if str(chosen.get(name)) in ("1", "true", "yes") else "off"  # noqa: E731
    return [f"| Sales answers | model `{chosen.get('KP_LLM_MODEL')}`, embeddings `{chosen.get('KP_EMBED_MODEL')}`; "
            f"query rewriting {on('KP_QUERY_REWRITE')}, reranking {on('KP_RERANK')}, model thinking "
            f"{'off' if str(chosen.get('KP_LLM_THINK')) == '0' else chosen.get('KP_LLM_THINK')} "
            f"(`services/opsatlas_sales/profile.json`) |"]


def _routes_and_catalogue() -> list[str]:
    from assistant.api.access import manifest
    from assistant.iam import catalogue
    from assistant.iam import roles as seeds
    saved = dict(os.environ)
    os.environ.update({"SME_TIBI_VOICE_URL": "http://127.0.0.1:9", "SALES_GOVERNANCE_AUTO_REVIEW": "0"})
    try:
        from services.opsatlas_sales.app import create_sales_app
        with tempfile.TemporaryDirectory() as tmp:
            app = create_sales_app(Path(os.path.realpath(tmp)) / "sales")
            kinds = Counter(row["kind"] for row in manifest(app))
    finally:
        os.environ.clear()
        os.environ.update(saved)
    reserved = sum(1 for p in catalogue.PERMISSIONS.values() if p.reserved)
    routes = ", ".join(f"{n} {k}" for k, n in sorted(kinds.items(), key=lambda kv: -kv[1]))
    return [f"| Workspace routes | {sum(kinds.values())} classified: {routes} (`assistant.api.access.manifest`) |",
            f"| Permission catalogue | version {catalogue.VERSION}: {len(catalogue.KEYS)} permissions, {reserved} reserved "
            f"(guard nothing yet); role seeds version {seeds.SEED_VERSION}, {len(seeds.BUILTIN)} built-in roles |"]


def block() -> str:
    rows = ["| Fact | Value |", "|---|---|", *_engine(), *_profile(), *_routes_and_catalogue()]
    return "\n".join([START, *rows, END])


def page_with(text: str, generated: str) -> str:
    if START in text and END in text:
        head, rest = text.split(START, 1)
        return head + generated + rest.split(END, 1)[1]
    raise SystemExit(f"{PAGE.name} has no release-facts markers")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated, text = block(), PAGE.read_text()
    if args.write:
        PAGE.write_text(page_with(text, generated))
    elif args.check:
        if page_with(text, generated) != text:
            print(f"{PAGE.name} is stale: run python scripts/release_facts.py --write")
            return 1
    else:
        print(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
